baseurl = "https://www.gotostepone.com/"
languageCode = "en-us"
title = "Step One"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Joshua Bradley"
    email = "josh@gotostepone.com"
    twitter = "@airjoshb"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5